[BB-2961] [BD-05] [TNL-7577] Added a templating mixin
edx/edx-ora2 pull request #1502
Opened 2020-09-19 00:57 UTC by farhaanbukhsh

This helps to interact with Studio API to give a list of presets

**TL;DR -** [ This change help us to populate multiple presets in studio ]

**What changed?**

- [ Added a templating Mixin to help  with populating multiple presets ]

**Developer Checklist**
- [ ] Reviewed the [release process](./release_process.md)
- [ ] Translations up to date
- [ ] JS minified, SASS compiled
- [ ] Test suites passing on Jenkins
- [ ] Bumped version number in [setup.py](../setup.py) and [package.json](../package.json)

JIRA: [TNL-7577](https://openedx.atlassian.net/browse/TNL-7577)

**Screenshot**:
![image](https://user-images.githubusercontent.com/7670449/93655463-1deb4e80-fa41-11ea-8dc3-44c32bbdc2d0.png)

![image](https://user-images.githubusercontent.com/7670449/93655469-280d4d00-fa41-11ea-97d5-2e95f9bd82c0.png)

2020-09-19 00:57 UTC, edx-webhook commented
Thanks for the pull request, @farhaanbukhsh! I've created [BLENDED-595](https://openedx.atlassian.net/browse/BLENDED-595) to keep track of it in Jira.   More details are on the [BD-05](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529970851/BD-05+ORA+v3+Usability+Moderation) project page.

When this pull request is ready, tag your edX technical lead.

<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->

2020-09-23 19:35 UTC, giovannicimolin commented on openassessment/xblock/openassessmentblock.py
> +    VALID_ASSESSMENT_TYPES_DISPLAY_NAMES = {
Can you add the types from the mockups and give them more descriptive names here?

2020-09-28 20:15 UTC, giovannicimolin requested changes
Changes look good, and seem to be working just fine in the devstack.

A few things to improve:
- The item ordering is not as in the mockups:
![image](https://user-images.githubusercontent.com/27893385/94481298-e2bded80-01ad-11eb-9fc9-6eeabaf95e81.png)
- We should change from `Open Response Assessment` to `Basic Open Response Assessment Template` as in the mockups.
- Fix quality issues (check CI run for details)
- Run `make extract_translations` and commit the result.

2020-09-28 20:15 UTC, giovannicimolin commented on openassessment/xblock/openassesment_template_mixin.py
> +        "self-to-staff": _("Self Assessment to Peer Assessment")
```suggestion
        "self-to-staff": _("Self Assessment to Staff Assessment")
```

2020-09-28 22:12 UTC, farhaanbukhsh commented
> Changes look good, and seem to be working just fine in the devstack.
> 
> A few things to improve:
> 
> * The item ordering is not as in the mockups:
>   ![image](https://user-images.githubusercontent.com/27893385/94481298-e2bded80-01ad-11eb-9fc9-6eeabaf95e81.png)

Done 

> * We should change from `Open Response Assessment` to `Basic Open Response Assessment Template` as in the mockups.

This can be done on studio side https://github.com/edx/edx-platform/blob/f7ddced9f83191ebcdcd736a22583ed020b10993/cms/djangoapps/contentstore/views/component.py#L294
at this line we can pass a custom name . This actually is taking the name of the xblock.

> * Fix quality issues (check CI run for details)

Done 

> * Run `make extract_translations` and commit the result.

Done


Hey @giovannicimolin  I have addressed your comments :) Please let me know.

2020-09-29 12:54 UTC, giovannicimolin commented
@farhaanbukhsh The item ordering is still not fixed. Can you follow the mockups linked in the ticket? 
The image I've posted is a screenshot showing the wrong positioning.

2020-09-29 13:12 UTC, giovannicimolin approved these changes
:+1:

- [x] I tested this:
1. Checked out this branch and installed on devstack.
2. Got into Studio, create a course.
3. Clicked on `Open Responses` button (I'm also using https://github.com/edx/edx-platform/pull/25012).
4. Checked that the templates described in the mockup are rendered.
![image](https://user-images.githubusercontent.com/27893385/94562703-0891d380-023c-11eb-9bcb-6b2c089e2fd2.png)
5. Checked that each template correctly configures the ORA block.
- [x] I read through the code
- [x] I checked for accessibility issues: Basic checks on items added.
- [ ] Includes documentation: No :x:. We need to update the ORA documentation later.

@farhaanbukhsh I think this is enough for changes in this repo, though we don't exactly match 1:1 the mockups.

A few requests **before** asking for upstream review:
1. Update the PR description to use our template.
2. Add screenshots.

2020-09-29 17:55 UTC, farhaanbukhsh commented
> @farhaanbukhsh The item ordering is still not fixed. Can you follow the mockups linked in the ticket?
> The image I've posted is a screenshot showing the wrong positioning. It might be local to my setup, can you post a screenshot?

You are right I thought it would have fixed it anyhow I investigated and there doesn't seem to be a way to keep the order intact since it gets converted into a string at the UI level.

https://github.com/edx/edx-platform/blob/master/cms/templates/container.html#L45

so I don't know if we can have a control over it.

2020-11-23 22:32 UTC, jnlapierre approved these changes
LGTM

2020-11-27 14:08 UTC, giovannicimolin commented
@farhaanbukhsh Can you fix the merge conflicts here?

2020-11-29 12:56 UTC, farhaanbukhsh commented
> @farhaanbukhsh Can you fix the merge conflicts here?

Done 😄

2020-12-01 21:26 UTC, merged