[BD-05][EDUCATOR-5596] Remove tinymcev5 and use the existing one from the platform
edx/edx-ora2 pull request #1601
Opened 2021-02-25 17:39 UTC by shimulch

Description goes here. e.g. This PR contains the LibraryContent XBlock, which allows to display library content in a course.

**JIRA tickets**: If there is a related publicly viewable JIRA ticket, mention that here. Also mention the OSPR ticket
number here once it gets created (after you open the PR), if applicable. Otherwise omit this.

**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.

**Dependencies**: None

**Screenshots**: Always include screenshots if there is any change to the UI.

**Sandbox URL**: TBD - sandbox is being provisioned.

**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.

**Testing instructions**:

1. Step by step manual setup/testing/verification instructions go here.
2. Step 2

**Author notes and concerns**:

1. We are aware that there is a glitch affecting the UI for this feature in the following way: ...
   Currently looking for ways to fix it.
2. We tried to optimize for accessibility, but there are still some open questions: ...

**Reviewers**
- [ ] (OpenCraft internal reviewer's GitHub username goes here)
- [ ] edX reviewer[s] TBD

**Settings**
```yaml
EDXAPP_FEATURES:
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
```

2021-02-25 17:39 UTC, edx-webhook commented
Thanks for the pull request, @shimulch! I've created [BLENDED-778](https://openedx.atlassian.net/browse/BLENDED-778) to keep track of it in Jira.   More details are on the [BD-05](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529970851/BD-05+ORA+v3+Usability+Moderation) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2021-02-25 18:09 UTC, giovannicimolin commented on openassessment/xblock/static/js/src/lms/editors/oa_editor_tinymce.js
> +        // this.elements.tinymce()
@shimulch Please remove this comment

2021-02-25 18:11 UTC, giovannicimolin requested changes
Minor nits. 

Can you also remove `tinymce` from the `package.json` file and add a version bump?

2021-02-25 18:11 UTC, giovannicimolin commented on openassessment/xblock/static/js/src/lms/editors/oa_editor_tinymce.js
> +    // as tinymce is not available, we need to load them
```suggestion
    // If tinymce is not available, we need to load it
```

2021-02-26 08:19 UTC, shimulch commented on openassessment/xblock/static/js/src/lms/editors/oa_editor_tinymce.js
> +        // this.elements.tinymce()
Removed

2021-02-26 08:19 UTC, shimulch commented on openassessment/xblock/static/js/src/lms/editors/oa_editor_tinymce.js
> +    // as tinymce is not available, we need to load them
Updated.

2021-02-26 08:20 UTC, shimulch commented
@giovannicimolin, I've added content styling CSS for tinyMCE. Hopefully, it will look a bit nicer now.
Also, removed tinymce from package.json & added version bumps.

2021-02-26 20:04 UTC, giovannicimolin approved these changes
:+1:

- [x] I tested this:
1. Tested that the editor works on LMS and studio.
2. Checked that text is nicely displayed in the readonly version of the editor.
- [x] I read through the code
- [x] I checked for accessibility issues: fixes issues caused by previous implementation.
- [ ] ~~Includes documentation~~ NA

2021-02-27 12:03 UTC, shimulch commented
@giovannicimolin, I've tested your commit that fixes the whitespace issue. LGTM 👍🏽 Thanks for figuring out a way to achieve that.

2021-03-02 18:26 UTC, jnlapierre commented
Please resolve merge conflicts and we will finalize the review.

2021-03-02 19:16 UTC, jnlapierre approved these changes
LGTM

2021-03-02 19:16 UTC, merged