[WIP][BD-05][TNL-7915][BB-3611] Improve ZIP File content structure
edx/edx-ora2 pull request #1610
Opened 2021-03-18 23:36 UTC by 0x29a

Description goes here. e.g. This PR contains the LibraryContent XBlock, which allows to display library content in a course.

**JIRA tickets**: If there is a related publicly viewable JIRA ticket, mention that here. Also mention the OSPR ticket
number here once it gets created (after you open the PR), if applicable. Otherwise omit this.

**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.

**Dependencies**: None

**Screenshots**: Always include screenshots if there is any change to the UI.

**Sandbox URL**: TBD - sandbox is being provisioned.

**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.

**Testing instructions**:

1. Step by step manual setup/testing/verification instructions go here.
2. Step 2

**Author notes and concerns**:

1. We are aware that there is a glitch affecting the UI for this feature in the following way: ...
   Currently looking for ways to fix it.
2. We tried to optimize for accessibility, but there are still some open questions: ...

**Reviewers**
- [ ] (OpenCraft internal reviewer's GitHub username goes here)
- [ ] edX reviewer[s] TBD

**Settings**
```yaml
EDXAPP_FEATURES:
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
```

2021-03-18 23:36 UTC, edx-webhook commented
Thanks for the pull request, @0x29a! I've created [BLENDED-799](https://openedx.atlassian.net/browse/BLENDED-799) to keep track of it in Jira.   More details are on the [BD-05](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529970851/BD-05+ORA+v3+Usability+Moderation) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2021-04-02 16:55 UTC, giovannicimolin reviewed
@0x29a I'm testing this with a test course which has multiple ORA and some units/sub-units to test possible edge cases.

Here's the course export: 
[course.19o_d71t.tar.gz](https://github.com/edx/edx-ora2/files/6250522/course.19o_d71t.tar.gz)

And this is a ZIP file export generated for this course:
**With anonymous ID:**
[OpenCraft_Test_tests_submission_files_2021-04-02-1544.zip](https://github.com/edx/edx-ora2/files/6250527/OpenCraft_Test_tests_submission_files_2021-04-02-1544.zip)

**With username::**
[OpenCraft_Test_tests_submission_files_2021-04-02-1542.zip](https://github.com/edx/edx-ora2/files/6250529/OpenCraft_Test_tests_submission_files_2021-04-02-1542.zip)

----

So far things seem okay. I'll keep digging the course and implementation.

2021-04-02 17:26 UTC, giovannicimolin requested changes
@0x29a I found some issues with the export.

Using this course (expanded from the first one I've posted above):  [course.830itub8.tar.gz](https://github.com/edx/edx-ora2/files/6250614/course.830itub8.tar.gz)

I found and issue with the filename that's causing these issues:
1. The submissions in the second folder (`[1]Section 1, [2]Subsection 2, [2]Unit`) start with index 2, even when there's a single ORA in the unit.
2. The submissions in the first folder (`[1]Section 1, [2]Subsection 2, [1]Unit` - this is a unit with 3 ORAs) have all the same index (`1`). This is causing a name clash issue and not all submissions are being exported properly. I'm submitting the assessments with 2 users.
  * Expected for `[1]Section 1, [2]Subsection 2, [1]Unit`: 6 files (2 for each ORA).
  * What's comes in the ZIP file: 
![image](https://user-images.githubusercontent.com/27893385/113438517-1a0c9180-93bf-11eb-9913-e3c084cb566a.png)
  * What's extracted (files with the same name cause filesystem conflicts):
![image](https://user-images.githubusercontent.com/27893385/113438562-30b2e880-93bf-11eb-894f-d70aba2d44ee.png)

Additionally, the `CSV` file contents aren't very clear. Is there a real need for it? Was it in the original requirements? If not, we can probably remove it.

2021-04-05 09:11 UTC, 0x29a commented
@giovannicimolin, thanks for the review.

In https://github.com/edx/edx-ora2/pull/1610/commits/7c45194ceab9598a8d50894c23a76729ed42916c commit I fixed typo in `_submission_filepath` function that was leading to incorrect ORA indexes in filename: `ora_path_info["unit_index"]` -> `ora_path_info["ora_index"]`.

Also, I added block type check here to prevent counting non-ORA blocks:
https://github.com/edx/edx-ora2/blob/7c45194ceab9598a8d50894c23a76729ed42916c/openassessment/data.py#L974-L984

And finally, I added handling of two edge cases:
1. When ORA block was removed from course, but submission is still there.
2. When section/sub-section/unit is empty.

2021-04-05 14:50 UTC, 0x29a commented on openassessment/data.py
> +        return path_info
Note: this wasn't covered with tests because it relies on platform internals.

2021-04-05 14:51 UTC, 0x29a commented on openassessment/data.py
> +        return {user["student_id"]: user["path_id"] for user in users}
Note: this wasn't covered with tests as well, since it relies on `ExternalId` model from Open edX core.

2021-04-05 15:01 UTC, giovannicimolin approved these changes
:+1:

- [x] I tested this:
1. Checked out this branch along with the https://github.com/edx/edx-platform/pull/27218.
2. Create a course structure that trigger edge cases with multiple ORAs. Export here: 
[course.7nx5cez9.tar.gz](https://github.com/edx/edx-ora2/files/6258759/course.7nx5cez9.tar.gz)
3. Submitted responses to the ORAs using `edx` and `verified` users. 
4. Exported the ZIP file (no PII - default): 
[OpenCraft_Test_tests_submission_files_2021-04-05-1352.zip](https://github.com/edx/edx-ora2/files/6258765/OpenCraft_Test_tests_submission_files_2021-04-05-1352.zip)
5. Enabled `ENABLE_ORA_USERNAMES_ON_DATA_EXPORT` and exported the same file again: 
[OpenCraft_Test_tests_submission_files_2021-04-05-1424.zip](https://github.com/edx/edx-ora2/files/6258773/OpenCraft_Test_tests_submission_files_2021-04-05-1424.zip)
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ NA
- [x] Includes documentation: docstrings. User documentation coming up on follow-up ticket.

@0x29a LGTM. :+1: 
Can you check why the sandbox is failing? https://manage.opencraft.com/instance/25930/

@jnlapierre @mattcarter This is ready for review.

2021-04-05 15:42 UTC, 0x29a commented
@giovannicimolin
> Can you check why the sandbox is failing? https://manage.opencraft.com/instance/25930/

Most likely, it's because I rebased the branch right after PR creation and Ocim was trying to check out to commit that wasn't a part of git tree. I updated it and created a new app server.

2021-04-12 18:06 UTC, jnlapierre approved these changes
LGTM and nice job cleaning up and refactoring some of the code to shared methods.

2021-05-14 15:11 UTC, jnlapierre approved these changes
LGTM

2021-05-14 15:11 UTC, merged