feat: add toggle feature for reusing rubics
edx/edx-ora2 pull request #1634
Opened 2021-05-20 03:28 UTC by leangseu-edx

- Create a django waffle addressable via the admin dashboard 
- Follow examples in code on approach
- Name the waffle openresponseassessment.enable_reuse_rubric

JIRA: [EDUCATOR-5751](https://openedx.atlassian.net/browse/EDUCATOR-5751)

**What changed?**

- Added a `togglable_reuse_rubric` annotation to the `student_view` of `edx-ora2`
- The `toggle_implementation` was documented as `WaffleFlag`. I made personal judgement based on this [document](https://edx.readthedocs.io/projects/edx-toggles/en/latest/how_to/implement_the_right_toggle_type.html).

**Developer Checklist**

- [ ] Reviewed the [release process](https://github.com/edx/edx-ora2/blob/master/.github/release_process.md)
- [ ] Translations and JS/SASS compiled
- [ ] Bumped version number in [setup.py](https://github.com/edx/edx-ora2/blob/a62e81a9b0d89223476967ec3c27f3557a850735/setup.py#L39) and [package.json](https://github.com/edx/edx-ora2/blob/a62e81a9b0d89223476967ec3c27f3557a850735/package.json#L3)

**Testing Instructions**

1. Create a waffle flag on the admin page - _/admin/waffle/flag/_
2. Name `openresponseassessment.reuse_rubric`
3. Set everyone to `Yes` or `No` to verify the test
4. Put a break point at [this line](https://github.com/edx/edx-ora2/blob/9f39d4e97fee57483bde3967afc812a3a04ef378/openassessment/xblock/test/test_reuse_rubric.py#L18) to verify that `self.is_reuse_rubric_enabled` is `True/False` respectively to the setting on number **3**.

**NOTE**: Due to local setup difficulty, I cannot get `make test` to pass but all the errors are from other test files than the one changed.

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ] I've done a visual code review
- [ ] I've tested the new functionality

FYI: @edx/masters-devs-gta

2021-05-20 18:02 UTC, nsprenkle requested changes
Note a typo. I also think a decorator is maybe not the way we want to do this (and this is my bad for not pointing out in the example) because we don't really care about enabling this per-view. It really only affects the studio view so we could use a pattern more similar to enabling team submissions in the studio editor.

2021-05-24 21:18 UTC, nsprenkle commented on openassessment/xblock/reuse_rubric_mixin.py
> +class ReuseRubricMixin:
I believe this class is unnecessary. You're already creating `is_reuse_rubric_enabled` in `config_mixin` which `OpenAssessment` has access to. I think you can just delete this file and mixin import and everything will still work.

2021-05-24 21:18 UTC, nsprenkle commented on settings/base.py
> +    # Set to True to enable this features
Update this comment to explain what the feature does, bonus points if you link to an epic
```suggestion
    # Set to True to enable copying rubric data from existing ORAs <JIRA-ticket>
```

2021-05-25 16:25 UTC, jansenk commented on openassessment/xblock/config_mixin.py
> +        # .. toggle_use_cases: vip
I think our use case is actually monitored rollout: https://open-edx-proposals.readthedocs.io/en/latest/oep-0017-bp-feature-toggles.html#use-case-3-ops-monitored-rollout

2021-05-25 16:27 UTC, jansenk commented on settings/base.py
> +    # Set to True to enable copying rubric data from existing ORAs <JIRA-ticket>
<JIRA-ticket>

2021-05-25 17:04 UTC, leangseu-edx commented on openassessment/xblock/test/test_config_mixin.py
> +        *list(itertools.product([True, False], repeat=3))
I was following other test of that files. Maybe I should make a ticket for adding None to all of other tests as well.

2021-05-25 19:17 UTC, nsprenkle approved these changes
Looks good. Have verified new behavior locally 👍

2021-05-25 19:18 UTC, nsprenkle commented
A reminder to check the release checklist, coordinate with team, and and do a version bump before you merge.

2021-05-25 20:24 UTC, merged